### ISSUE TITLE
Should the blueprint create the Manta dir if it doesn't exist?

### ISSUE THREAD

**Issue by misterbisson** [tgross/triton-mysql#4]
To avoid this error on paths/directories that don't yet exist:

```
Traceback (most recent call last):
  File "/bin/triton-mysql.py", line 957, in <module>
    locals()[sys.argv[1]]()
  File "/bin/triton-mysql.py", line 387, in create_snapshot
    manta_config.put_backup(backup_id, '/tmp/backup.tar')
  File "/bin/triton-mysql.py", line 200, in put_backup
    self.client.put_object(mpath, file=f)
  File "/usr/local/lib/python2.7/dist-packages/manta/client.py", line 353, in put_object
    raise errors.MantaAPIError(res, content)
manta.errors.MantaAPIError: (DirectoryDoesNotExist) /<username>/stor/triton-mysql does not exist
```

**Comment by tgross** [comment]
I wasn't sure on this one myself and it's kind of an ugly problem. There's a fairly large section of the makefile dedicated to setting up the Manta account, role, policy, directory, and assigning all of those the permissions: https://github.com/tgross/triton-mysql/blob/3bbad37257a39507aaaf0b80048da7f5a882ee08/makefile#L49-L67

If we tried to do those steps inside the container then the container would need to have keys that are associated with policies that permit the container to create new accounts, which misses the point of having a dedicated account. Even if we just create the directory, that implies that the container has permissions to create directories at a level higher up in the directory tree than we've intended to give it permission for.

I'm certainly open to suggestion here but solving the problem to set up the permissions automatically via the container pretty much ends up recursively giving out container "root" on Manta.

**Comment by misterbisson** [comment]
> solving the problem to set up the permissions automatically via the container pretty much ends up recursively giving out container "root" on Manta

Right. I'd lazily been using my root/primary account for the Manta access, but that's not ideal and we shouldn't make assumptions based on less than ideal practice.

It was a question, it's been answered, I'm closing.
