### ISSUE TITLE
Usage without Manta possible?

### ISSUE THREAD

**Issue by adri** [tgross/triton-mysql#6]
When starting up the compose file I get the following error because I didn't configure Manta.

```
config_consul_1 is up-to-date
Starting config_mysql_1
Attaching to config_mysql_1
mysql_1 | Traceback (most recent call last):
mysql_1 |   File "/bin/triton-mysql.py", line 953, in <module>
mysql_1 |     manta_config = Manta()
mysql_1 |   File "/bin/triton-mysql.py", line 189, in __init__
mysql_1 |     signer=self.signer)
mysql_1 |   File "/usr/local/lib/python2.7/dist-packages/manta/client.py", line 140, in __init__
mysql_1 |     assert account, 'account'
mysql_1 | AssertionError: account
```

Is it a hard dependency to use Manta? I read that the Manta environment variables are optional but I didn't find a way to disable it.

**Comment by adri** [comment]
Mh sorry it is stated explicitly that it is meant to run on the Joyent's Triton platform. Didn't see that. Closing.

**Comment by tgross** [comment]
> I read that the Manta environment variables are optional but I didn't find a way to disable it.

They should be, so this looks to be a bug. That being said, you lose the ability to bootstrap replication without having Manta. (You could modify `triton-mysql.py` to use a different object store of course.)
